# Site settings
title: Jekyll Dynamic Menu
email: donirby@live.com
description: A dynamically generated hierarchical menu in jekyll without plugins
baseurl: "/jekyll-dynamic-menu"
url: "http://donirby.github.io/jekyll-dynamic-menu"
github_username:  donirby
